services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airline
    volumes:
      - ./db:/home/scripts
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  passport_api:
    image: wiremock/wiremock:3.9.1
    ports:
      - 8081:8080
    volumes:
      - ./passport_api:/home/wiremock

  airline_api_dev:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/airline
      - PASSPORT_API=http://passport_api:8080

volumes:
  pgadmin_data:
